# Look ma, no bloat!
FROM scratch

# Leave this, it copies your application source to the root
ADD . /

# The node binary is copied to /, as is your app
WORKDIR /

# Feel free to change this, it's just a suggestion
ENTRYPOINT ["/node"]
